### ISSUE TITLE
User Registeration Workflow

### ISSUE THREAD

**Issue by maniyalraj** [maniyalraj/lingayat-matrimony#2]
As a `User` I want to `Register myself` so that I can use the application and share my details with other users.

**Comment by maniyalraj** [comment]
Acceptance Criteria:

- [ ] The Process must be short, at most email, password, contact info and DOB.

- [ ] Username should be either of email or password, no new username will be acceptable

- [ ] Input should be 1st level validated
